import { Bicycle, Reservation } from "./types"

export const initialBicycles: Bicycle[] = [
  { id: "b1", name: "Trail Blazer 500", price: 15, category: "VTT" },
  { id: "b2", name: "Urban Glide Pro", price: 10, category: "City" },
  { id: "b3", name: "EcoVolt E-200", price: 25, category: "Electric" },
  { id: "b4", name: "Mountain King X", price: 18, category: "VTT" },
  { id: "b5", name: "City Cruiser Lite", price: 8, category: "City" },
  { id: "b6", name: "Thunder Bolt E-500", price: 30, category: "Electric" },
  { id: "b7", name: "Rock Hopper 300", price: 14, category: "VTT" },
  { id: "b8", name: "Metro Breeze", price: 9, category: "City" },
]

export const initialReservations: Reservation[] = [
  {
    id: "r1",
    customerName: "Yassine El Amrani",
    phoneNumber: "+212 612-345678",
    duration: 3,
    reservationDate: "2026-02-13",
    bicycleCategory: "VTT",
    status: "Pending",
  },
  {
    id: "r2",
    customerName: "Fatima Benali",
    phoneNumber: "+212 655-112233",
    duration: 2,
    reservationDate: "2026-02-13",
    bicycleCategory: "Electric",
    status: "Confirmed",
  },
  {
    id: "r3",
    customerName: "Omar Chakir",
    phoneNumber: "+212 661-998877",
    duration: 5,
    reservationDate: "2026-02-12",
    bicycleCategory: "City",
    status: "Annulled",
  },
  {
    id: "r4",
    customerName: "Amina Tazi",
    phoneNumber: "+212 677-445566",
    duration: 1,
    reservationDate: "2026-02-14",
    bicycleCategory: "VTT",
    status: "Pending",
  },
  {
    id: "r5",
    customerName: "Karim Idrissi",
    phoneNumber: "+212 622-334455",
    duration: 4,
    reservationDate: "2026-02-14",
    bicycleCategory: "Electric",
    status: "Pending",
  },
  {
    id: "r6",
    customerName: "Laila Mansouri",
    phoneNumber: "+212 699-556677",
    duration: 2,
    reservationDate: "2026-02-11",
    bicycleCategory: "City",
    status: "Confirmed",
  },
  {
    id: "r7",
    customerName: "Hassan Berrada",
    phoneNumber: "+212 644-778899",
    duration: 6,
    reservationDate: "2026-02-15",
    bicycleCategory: "VTT",
    status: "Pending",
  },
  {
    id: "r8",
    customerName: "Nadia Filali",
    phoneNumber: "+212 633-221100",
    duration: 3,
    reservationDate: "2026-02-10",
    bicycleCategory: "Electric",
    status: "Confirmed",
  },
]
